{
 "title": "#Title#",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "label_values({container=\"#ContainerName#\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Alerts",
   "type": "alertlist",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(aap_affiliate_analytics_counter_handler_base_exceptions{container=\"#ContainerName#\", pod=~\"$pods\"}[$__rate_interval]))",
     "legendFormat": "Handler Exceptions ($pods)"
    }
   ]
  },
  {
   "title": "Kafka Health Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(aspnetcore_healthcheck_status{name=\"kafka\",container=\"#ContainerName#\", pod=~\"$pods\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Persistence Health Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(aspnetcore_healthcheck_status{name=\"Persistence\",container=\"#ContainerName#\", pod=~\"$pods\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group by (name) ((aspnetcore_healthcheck_status{name=\"Persistence\",container=\"#ContainerName#\", pod=~\"$pods\"}))",
     "legendFormat": "Persistence ($pods)"
    },
    {
     "expr": "group by (name) ((aspnetcore_healthcheck_status{name=\"kafka\",container=\"#ContainerName#\", pod=~\"$pods\"}))",
     "legendFormat": "Kafka ($pods)"
    }
   ]
  },
  {
   "title": "Excess CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"#ContainerName#\"}) - sum by(pod) (cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{container=\"#ContainerName#\"}) > 0"
    }
   ]
  },
  {
   "title": "Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(system_runtime_cpu_usage{container=\"#ContainerName#\", pod=~\"$pods\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{container=\"#ContainerName#\", pod=~\"$pods\"}",
     "legendFormat": "CPU Usage ($pods)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(dotnet_total_memory_bytes{container=\"#ContainerName#\", pod=~\"$pods\"})/1e+9",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(dotnet_total_memory_bytes{container=\"#ContainerName#\", pod=~\"$pods\"}/1e+9)",
     "legendFormat": "Memory Usage (In GB) ($pods)"
    }
   ]
  },
  {
   "title": "Kafka Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Messages Produced",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_partition_transmitted_message_total{topic=\"#LoggingTopic#\",container=\"#ContainerName#\", pod=~\"$pods\"}[$__rate_interval]))",
     "legendFormat": "Logging (#LoggingTopic#) ($pods)"
    }
   ]
  },
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  }
 ]
}